provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  render:
    lang: python3
    handler: ./render
    image: alexcourouble/render
  assets:
    lang: python3
    handler: ./assets
    image: alexcourouble/assets
